/**
 * Dynamic study loader
 * Automatically loads studies without requiring manual imports
 * Also supports in-memory test studies from admin preview
 */

import { StudyMetadata } from './types';
import { testStudyRegistry } from '@/services/testStudyRegistry';

/**
 * Registry of available studies
 * This file is auto-generated by the import process
 */
export const AVAILABLE_STUDIES = [
  'prob-gym',
  'gerstenberg2012ping-exp1',
  'jern2017people-exp1',
  'Olympics2025-exp2',
  'Olympics2025-exp3',
  'Wong2025Modeling-exp1',
] as const;

export type StudySlug = typeof AVAILABLE_STUDIES[number];

/**
 * Dynamically import study metadata
 * Checks test registry first for TEST_ prefixed studies
 */
export async function loadStudyMetadata(slug: string): Promise<StudyMetadata | null> {
  // Check if this is a test study
  if (testStudyRegistry.isTestStudy(slug)) {
    console.log(`[loadStudyMetadata] Detected test study: ${slug}`);
    const testStudy = testStudyRegistry.getStudyBySlug(slug);

    if (testStudy) {
      console.log(`[loadStudyMetadata] Found test study in registry: ${testStudy.metadata.title}`);
      return testStudy.metadata;
    } else {
      console.error(`[loadStudyMetadata] Test study not found in registry: ${slug}`);
      // Try to get all studies to debug
      const allStudies = testStudyRegistry.getAllStudies();
      console.log(`[loadStudyMetadata] Registry has ${allStudies.length} studies:`, allStudies.map(s => s.slug));
      return null;
    }
  }

  // Load from file system for regular studies
  try {
    const { metadata } = await import(`@/studies/${slug}/metadata`);
    return metadata;
  } catch (error) {
    console.error(`Failed to load metadata for study: ${slug}`, error);
    return null;
  }
}

/**
 * Dynamically import study scenarios
 * Checks test registry first for TEST_ prefixed studies
 */
export async function loadStudyScenarios(slug: string): Promise<any[] | null> {
  // Check if this is a test study
  if (testStudyRegistry.isTestStudy(slug)) {
    const testStudy = testStudyRegistry.getStudyBySlug(slug);
    return testStudy ? testStudy.scenarios : null;
  }

  // Load from file system for regular studies
  try {
    const { scenarios } = await import(`@/studies/${slug}/scenarios`);
    return scenarios;
  } catch (error) {
    console.error(`Failed to load scenarios for study: ${slug}`, error);
    return null;
  }
}

/**
 * Dynamically import study config
 * Test studies don't have config files, so return null for them
 */
export async function loadStudyConfig(slug: string): Promise<any | null> {
  // Test studies don't have config files
  if (testStudyRegistry.isTestStudy(slug)) {
    return null;
  }

  // Load from file system for regular studies
  try {
    const config = await import(`@/studies/${slug}/config.json`);
    return config.default || config;
  } catch (error) {
    console.error(`Failed to load config for study: ${slug}`, error);
    return null;
  }
}

/**
 * Load all available studies
 */
export async function loadAllStudies(): Promise<StudyMetadata[]> {
  const studies = await Promise.all(
    AVAILABLE_STUDIES.map(slug => loadStudyMetadata(slug))
  );
  return studies.filter((s): s is StudyMetadata => s !== null);
}

/**
 * Check if a study exists
 * Also checks test registry for TEST_ prefixed studies
 */
export function isValidStudy(slug: string): boolean {
  // Check if it's a test study
  if (testStudyRegistry.isTestStudy(slug)) {
    return testStudyRegistry.getStudyBySlug(slug) !== undefined;
  }

  // Check if it's a regular study
  return AVAILABLE_STUDIES.includes(slug as StudySlug);
}
